name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "v*-dev"
    paths-ignore:
      - "mkdocs.yml"
      - "docs/**"
      - "**.md"
      - "**.mdx"
      - "**.png"
      - "**.jpg"
      - "**.gif"
jobs:
  ci:
    uses: ./.github/workflows/ci-common.yaml
    with:
      python-version: '3.10'
      upload-artifacts: true
