name: PR

on:
  pull_request:
    branches:
      - main
      - "v*-dev"
    paths-ignore:
      - "mkdocs.yml"
      - "docs/**"
      - "**.md"
      - "**.mdx"
      - "**.png"
      - "**.jpg"
      - "**.gif"

jobs:
  ci-macos:
    uses: ./.github/workflows/ci-common.yaml
    with:
      python-version: '3.10'
      pr: true
      windows-toolkit-name: ''
