name: Tag Release
on:
  push:
    tags: ["*.*.*"]
jobs:
  tag-macos:
    uses: ./.github/workflows/ci-common.yaml
    with:
      python-version: '3.10'
      upload-artifacts: true
  release:
    runs-on: ubuntu-latest
    needs: tag-macos
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-*
          merge-multiple: true
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          fail_on_unmatched_files: true
          files: gpustack-*
